In [188]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [189]:
import pandas as pd

In [190]:
df = pd.read_csv("C:/Users/anbarasi/OneDrive/Documents/Downloads/ResaleFlatPricesBasedonApprovalDate19901999.csv")
df1 = pd.read_csv("C:/Users/anbarasi/OneDrive/Documents/Downloads/ResaleFlatPricesBasedonApprovalDate2000Feb2012.csv")
df2 =pd.read_csv("C:/Users/anbarasi/OneDrive/Documents/Downloads/ResaleFlatPricesBasedonRegistrationDateFromJan2015toDec2016.csv")
df3 = pd.read_csv("C:/Users/anbarasi/OneDrive/Documents/Downloads/ResaleFlatPricesBasedonRegistrationDateFromMar2012toDec2014.csv")

In [191]:
df.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price'],
      dtype='object')

In [192]:
df1.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price'],
      dtype='object')

In [193]:
df2.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date',
       'remaining_lease', 'resale_price'],
      dtype='object')

In [194]:
df3.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price'],
      dtype='object')

In [195]:

# Merging DataFrames (assuming they share common columns)
merge_df = pd.concat([df, df1, df2, df3], ignore_index=True)

In [196]:
# Reset the index
merge_df.reset_index(drop=True, inplace=True)

In [197]:
merge_df.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price',
       'remaining_lease'],
      dtype='object')

In [198]:
merge_df.head()

month        town flat_type block       street_name storey_range  \
0  1990-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
1  1990-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     04 TO 06   
2  1990-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     10 TO 12   
3  1990-01  ANG MO KIO    1 ROOM   309  ANG MO KIO AVE 1     07 TO 09   
4  1990-01  ANG MO KIO    3 ROOM   216  ANG MO KIO AVE 1     04 TO 06   

   floor_area_sqm      flat_model  lease_commence_date  resale_price  \
0            31.0        IMPROVED                 1977        9000.0   
1            31.0        IMPROVED                 1977        6000.0   
2            31.0        IMPROVED                 1977        8000.0   
3            31.0        IMPROVED                 1977        6000.0   
4            73.0  NEW GENERATION                 1976       47200.0   

   remaining_lease  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN

In [199]:
merge_df.dtypes

month                   object
town                    object
flat_type               object
block                   object
street_name             object
storey_range            object
floor_area_sqm         float64
flat_model              object
lease_commence_date      int64
resale_price           float64
remaining_lease        float64
dtype: object

In [200]:
merge_df.isnull().sum()

month                       0
town                        0
flat_type                   0
block                       0
street_name                 0
storey_range                0
floor_area_sqm              0
flat_model                  0
lease_commence_date         0
resale_price                0
remaining_lease        709050
dtype: int64

In [201]:
# droping remaining_lease missing values
merge_df = merge_df.dropna()
merge_df.isnull().sum()

month                  0
town                   0
flat_type              0
block                  0
street_name            0
storey_range           0
floor_area_sqm         0
flat_model             0
lease_commence_date    0
resale_price           0
remaining_lease        0
dtype: int64

In [202]:
merge_df.duplicated().sum()


np.int64(24)

In [203]:
merge_df[merge_df.duplicated()]


month             town flat_type block         street_name  \
657508  2015-01  KALLANG/WHAMPOA    3 ROOM    57       GEYLANG BAHRU   
659013  2015-02         TAMPINES    3 ROOM   403      TAMPINES ST 41   
660743  2015-04            BEDOK    4 ROOM   701  BEDOK RESERVOIR RD   
661093  2015-04         CLEMENTI    3 ROOM   714  CLEMENTI WEST ST 2   
662340  2015-05            BEDOK    3 ROOM   409     BEDOK NTH AVE 2   
662923  2015-05      JURONG WEST    3 ROOM   501   JURONG WEST ST 51   
663938  2015-06            BEDOK    3 ROOM   410     BEDOK NTH AVE 2   
664029  2015-06           BISHAN    4 ROOM   267        BISHAN ST 24   
665961  2015-07    CHOA CHU KANG    5 ROOM  690D  CHOA CHU KANG CRES   
667062  2015-08       ANG MO KIO    3 ROOM   473   ANG MO KIO AVE 10   
668318  2015-08        WOODLANDS    4 ROOM     8        MARSILING DR   
672342  2015-11      JURONG EAST    3 ROOM   243   JURONG EAST ST 24   
672944  2015-11         TAMPINES    4 ROOM  488B      TAMPINES ST 45   
673967  2015-12  KALLANG/WHAMPOA    5 ROOM    17        JLN TENTERAM   
675043  2016-01         CLEMENTI    3 ROOM   450      CLEMENTI AVE 3   
675524  2016-01         SENGKANG    4 ROOM  436D         FERNVALE RD   
676668  2016-02        SEMBAWANG    4 ROOM   467        ADMIRALTY DR   
677144  2016-03       ANG MO KIO    3 ROOM   333    ANG MO KIO AVE 1   
680156  2016-04         TAMPINES    3 ROOM   830      TAMPINES ST 82   
686851  2016-08  KALLANG/WHAMPOA    5 ROOM   103           JLN RAJAH   
687398  2016-08         TAMPINES    4 ROOM  168B          SIMEI LANE   
688890  2016-09         SENGKANG    4 ROOM  271A       SENGKANG CTRL   
692949  2016-12    BUKIT PANJANG    4 ROOM   447  BT PANJANG RING RD   
693738  2016-12         TAMPINES    4 ROOM   440      TAMPINES ST 43   

       storey_range  floor_area_sqm         flat_model  lease_commence_date  \
657508     16 TO 18            65.0           Improved                 1974   
659013     07 TO 09            69.0           Improved                 1985   
660743     10 TO 12            93.0     New Generation                 1980   
661093     10 TO 12            67.0     New Generation                 1980   
662340     07 TO 09            68.0     New Generation                 1980   
662923     01 TO 03            74.0            Model A                 1986   
663938     04 TO 06            68.0     New Generation                 1980   
664029     04 TO 06           104.0            Model A                 1992   
665961     13 TO 15           110.0           Improved                 2003   
667062     07 TO 09            67.0     New Generation                 1984   
668318     10 TO 12            88.0           Improved                 1976   
672342     01 TO 03            67.0     New Generation                 1983   
672944     07 TO 09           105.0            Model A                 1989   
673967     16 TO 18           105.0           Improved                 2001   
675043     04 TO 06            82.0     New Generation                 1980   
675524     13 TO 15            96.0            Model A                 2010   
676668     07 TO 09           102.0  Premium Apartment                 2001   
677144     04 TO 06            68.0     New Generation                 1981   
680156     01 TO 03            70.0         Simplified                 1986   
686851     07 TO 09           135.0            Model A                 1984   
687398     10 TO 12            94.0               DBSS                 2011   
688890     10 TO 12            93.0  Premium Apartment                 2010   
692949     07 TO 09           101.0            Model A                 1997   
693738     10 TO 12            84.0         Simplified                 1986   

        resale_price  remaining_lease  
657508      315000.0             58.0  
659013      350000.0             69.0  
660743      400000.0             64.0  
661093      300000.0             64.0  
662340      340000.0             

In [204]:
# remove duplicate
merge_df = merge_df.drop_duplicates()


In [205]:
merge_df.duplicated().sum() #after removing duplicate


np.int64(0)

In [206]:
merge_df.head()

month        town flat_type block        street_name storey_range  \
656847  2015-01  ANG MO KIO    3 ROOM   174   ANG MO KIO AVE 4     07 TO 09   
656848  2015-01  ANG MO KIO    3 ROOM   541  ANG MO KIO AVE 10     01 TO 03   
656849  2015-01  ANG MO KIO    3 ROOM   163   ANG MO KIO AVE 4     01 TO 03   
656850  2015-01  ANG MO KIO    3 ROOM   446  ANG MO KIO AVE 10     01 TO 03   
656851  2015-01  ANG MO KIO    3 ROOM   557  ANG MO KIO AVE 10     07 TO 09   

        floor_area_sqm      flat_model  lease_commence_date  resale_price  \
656847            60.0        Improved                 1986      255000.0   
656848            68.0  New Generation                 1981      275000.0   
656849            69.0  New Generation                 1980      285000.0   
656850            68.0  New Generation                 1979      290000.0   
656851            68.0  New Generation                 1980      290000.0   

        remaining_lease  
656847             70.0  
656848             65.0  
656849             64.0  
656850             63.0  
656851             64.0

In [207]:
merge_df.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price',
       'remaining_lease'],
      dtype='object')

In [208]:
important_features = [
    'floor_area_sqm',
    'flat_type',
    'storey_range',
    'town',
    'block',
    'lease_commence_date',
    'remaining_lease'
]


In [209]:
merge_df = merge_df.drop(['month', 'street_name', 'flat_model','block'], axis=1)


In [210]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [211]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [212]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [213]:
pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-packag

In [214]:
merge_df['flat_type'].unique()

array(['3 ROOM', '4 ROOM', '5 ROOM', '2 ROOM', 'EXECUTIVE', '1 ROOM',
       'MULTI-GENERATION'], dtype=object)

In [215]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [216]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
merge_df['flat_type_encoded'] = le.fit_transform(merge_df['flat_type'])

print(dict(zip(le.classes_, le.transform(le.classes_))))


{'1 ROOM': np.int64(0), '2 ROOM': np.int64(1), '3 ROOM': np.int64(2), '4 ROOM': np.int64(3), '5 ROOM': np.int64(4), 'EXECUTIVE': np.int64(5), 'MULTI-GENERATION': np.int64(6)}


In [217]:
merge_df.drop('flat_type', axis=1, inplace=True)

In [218]:
merge_df['town'].unique()

array(['ANG MO KIO', 'BEDOK', 'BISHAN', 'BUKIT BATOK', 'BUKIT MERAH',
       'BUKIT PANJANG', 'BUKIT TIMAH', 'CENTRAL AREA', 'CHOA CHU KANG',
       'CLEMENTI', 'GEYLANG', 'HOUGANG', 'JURONG EAST', 'JURONG WEST',
       'KALLANG/WHAMPOA', 'MARINE PARADE', 'PASIR RIS', 'PUNGGOL',
       'QUEENSTOWN', 'SEMBAWANG', 'SENGKANG', 'SERANGOON', 'TAMPINES',
       'TOA PAYOH', 'WOODLANDS', 'YISHUN'], dtype=object)

In [219]:
town_encoded = pd.get_dummies(merge_df['town'], prefix='town')
merge_df = pd.concat([merge_df, town_encoded], axis=1)
merge_df.drop('town', axis=1, inplace=True)

print("✅ One-Hot Encoding applied for 'town' column.")


✅ One-Hot Encoding applied for 'town' column.


In [220]:
merge_df['storey_range'].unique()


array(['07 TO 09', '01 TO 03', '13 TO 15', '10 TO 12', '04 TO 06',
       '19 TO 21', '16 TO 18', '22 TO 24', '25 TO 27', '28 TO 30',
       '34 TO 36', '46 TO 48', '31 TO 33', '37 TO 39', '43 TO 45',
       '40 TO 42', '49 TO 51'], dtype=object)

In [222]:
merge_df['storey_range']. unique()

array(['07 TO 09', '01 TO 03', '13 TO 15', '10 TO 12', '04 TO 06',
       '19 TO 21', '16 TO 18', '22 TO 24', '25 TO 27', '28 TO 30',
       '34 TO 36', '46 TO 48', '31 TO 33', '37 TO 39', '43 TO 45',
       '40 TO 42', '49 TO 51'], dtype=object)

In [223]:
storey_order = [
    '01 TO 03', '04 TO 06', '07 TO 09', '10 TO 12', '13 TO 15',
    '16 TO 18', '19 TO 21', '22 TO 24', '25 TO 27', '28 TO 30',
    '31 TO 33', '34 TO 36', '37 TO 39', '40 TO 42', '43 TO 45',
    '46 TO 48', '49 TO 51'
]

merge_df['storey_range_encoded'] = merge_df['storey_range'].map({v: i for i, v in enumerate(storey_order)})

print(merge_df[['storey_range', 'storey_range_encoded']].head())


       storey_range  storey_range_encoded
656847     07 TO 09                     2
656848     01 TO 03                     0
656849     01 TO 03                     0
656850     01 TO 03                     0
656851     07 TO 09                     2


In [224]:
merge_df.drop('storey_range', axis=1, inplace=True)


In [225]:
# Select only numerical columns
num_cols = merge_df.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [226]:
# Detect outliers using IQR method
outlier_cols = []

for col in num_cols:
    Q1 = merge_df[col].quantile(0.25)
    Q3 = merge_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    # Count outliers
    outliers = merge_df[(merge_df[col] < lower_limit) | (merge_df[col] > upper_limit)]
    if not outliers.empty:
        outlier_cols.append(col)

# Print result
if outlier_cols:
    print("Columns that contain outliers:", outlier_cols)
else:
    print("✅ No outliers detected in numeric columns.")


Columns that contain outliers: ['floor_area_sqm', 'resale_price', 'storey_range_encoded']


In [227]:
# Check skewness for numeric columns
skew_values = merge_df[['floor_area_sqm', 'resale_price','storey_range_encoded']].skew()

print("Skewness values:")
print(skew_values)


Skewness values:
floor_area_sqm          0.297575
resale_price            1.270726
storey_range_encoded    1.603200
dtype: float64


In [228]:
merge_df['resale_price'].head()

656847    255000.0
656848    275000.0
656849    285000.0
656850    290000.0
656851    290000.0
Name: resale_price, dtype: float64

In [229]:
import numpy as np
merge_df['floor_area_sqm'] = np.power(merge_df['floor_area_sqm'], 2)


In [230]:
# for right skew
import numpy as np

merge_df['floor_area_sqm'] = np.log1p(merge_df['floor_area_sqm'])
merge_df['resale_price'] = np.log1p(merge_df['resale_price'])

print("✅ Log transformation applied to right-skewed columns.")


✅ Log transformation applied to right-skewed columns.


In [231]:
merge_df['resale_price'].head()

656847    12.449023
656848    12.524530
656849    12.560248
656850    12.577640
656851    12.577640
Name: resale_price, dtype: float64

In [232]:
merge_df.dtypes

floor_area_sqm          float64
lease_commence_date       int64
resale_price            float64
remaining_lease         float64
flat_type_encoded         int64
town_ANG MO KIO            bool
town_BEDOK                 bool
town_BISHAN                bool
town_BUKIT BATOK           bool
town_BUKIT MERAH           bool
town_BUKIT PANJANG         bool
town_BUKIT TIMAH           bool
town_CENTRAL AREA          bool
town_CHOA CHU KANG         bool
town_CLEMENTI              bool
town_GEYLANG               bool
town_HOUGANG               bool
town_JURONG EAST           bool
town_JURONG WEST           bool
town_KALLANG/WHAMPOA       bool
town_MARINE PARADE         bool
town_PASIR RIS             bool
town_PUNGGOL               bool
town_QUEENSTOWN            bool
town_SEMBAWANG             bool
town_SENGKANG              bool
town_SERANGOON             bool
town_TAMPINES              bool
town_TOA PAYOH             bool
town_WOODLANDS             bool
town_YISHUN                bool
storey_r

In [233]:
merge_df['storey_range_encoded'].unique()

array([ 2,  0,  4,  3,  1,  6,  5,  7,  8,  9, 11, 15, 10, 12, 14, 13, 16])

In [234]:
merge_df['floor_area_sqm'].unique()

array([ 8.18896686,  8.43923165,  8.46842303,  8.40960798,  8.60831278,
        8.8135872 ,  8.58110652,  8.63515399,  9.04369529,  9.02183976,
        9.0653146 ,  9.14952823,  9.17003908,  9.19034173,  9.65669147,
        9.59164939,  9.85455988,  9.5583176 ,  9.62443481,  9.40104337,
        9.41914156,  7.61381868,  7.56889566,  8.15536212,  8.3490112 ,
        8.49719454,  8.78905071,  8.83782636,  8.86177531,  8.97739898,
        8.99974279,  9.26955223,  9.34574501,  9.3080114 ,  8.88544091,
        9.70412156,  9.6726268 ,  9.54144106,  9.60810927,  9.9944702 ,
        9.89757008, 10.3066166 ,  9.96726016,  9.28887425,  9.38277993,
        9.36434818,  9.10786458,  9.21044037,  9.5072547 ,  9.57505293,
        9.84001513, 10.00793765, 10.02131503, 10.31814363,  8.31801028,
        8.76420951,  9.08670273,  9.79573529,  9.45485395,  7.784057  ,
        7.47590597,  8.05102221,  8.28652137,  8.37953903,  8.95480275,
        9.23033906,  9.48993987,  9.64062817,  9.32696718,  9.25

In [235]:
merge_df['lease_commence_date'].unique()

array([1986, 1981, 1980, 1979, 1978, 1985, 1976, 1977, 2002, 1993, 1996,
       2006, 2003, 1982, 1974, 2010, 1987, 1984, 2000, 1989, 1995, 1992,
       1988, 1998, 1990, 1983, 2004, 1997, 2005, 1969, 1970, 1971, 1973,
       2009, 1999, 2001, 2008, 2007, 1975, 2011, 1968, 1967, 1972, 1991,
       2012, 1994, 1966, 2013])

In [236]:
merge_df['remaining_lease'].unique()

array([70., 65., 64., 63., 62., 69., 60., 61., 86., 77., 80., 90., 87.,
       66., 58., 94., 71., 68., 84., 73., 79., 76., 72., 82., 74., 67.,
       88., 81., 89., 53., 54., 55., 57., 93., 83., 85., 92., 91., 59.,
       95., 52., 51., 56., 75., 96., 78., 50., 97., 49., 48.])

In [237]:
merge_df['storey_range_encoded'].unique()

array([ 2,  0,  4,  3,  1,  6,  5,  7,  8,  9, 11, 15, 10, 12, 14, 13, 16])

In [238]:
X = merge_df.drop('resale_price', axis=1)  # all columns except resale_price
y = merge_df['resale_price']               # target variable


In [239]:
X.columns

Index(['floor_area_sqm', 'lease_commence_date', 'remaining_lease',
       'flat_type_encoded', 'town_ANG MO KIO', 'town_BEDOK', 'town_BISHAN',
       'town_BUKIT BATOK', 'town_BUKIT MERAH', 'town_BUKIT PANJANG',
       'town_BUKIT TIMAH', 'town_CENTRAL AREA', 'town_CHOA CHU KANG',
       'town_CLEMENTI', 'town_GEYLANG', 'town_HOUGANG', 'town_JURONG EAST',
       'town_JURONG WEST', 'town_KALLANG/WHAMPOA', 'town_MARINE PARADE',
       'town_PASIR RIS', 'town_PUNGGOL', 'town_QUEENSTOWN', 'town_SEMBAWANG',
       'town_SENGKANG', 'town_SERANGOON', 'town_TAMPINES', 'town_TOA PAYOH',
       'town_WOODLANDS', 'town_YISHUN', 'storey_range_encoded'],
      dtype='object')

In [240]:
y.tail()

693995    13.098073
693996    13.028055
693997    13.564483
693998    13.262127
693999    13.507627
Name: resale_price, dtype: float64

In [241]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [242]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [243]:
# 4️⃣ Train the model
# ---------------------------
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [244]:
# 4️⃣ Predict & evaluate
# ---------------------------
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [245]:
print("✅ Model Evaluation Results")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R² Score: {r2:.2f}")

✅ Model Evaluation Results
Mean Absolute Error (MAE): 0.08
Mean Squared Error (MSE): 0.01
R² Score: 0.88


In [246]:
# ---------------------------
# 🌳 Random Forest Regressor
# ---------------------------
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize and train model
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

# Predict
rf_pred = rf_model.predict(X_test)

# Evaluate
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_r2 = r2_score(y_test, rf_pred)

print("🌳 Random Forest Results")
print(f"MAE: {rf_mae:.2f}")
print(f"MSE: {rf_mse:.2f}")
print(f"R²: {rf_r2:.2f}")


🌳 Random Forest Results
MAE: 0.05
MSE: 0.00
R²: 0.94


In [247]:
# ---------------------------
# ⚙️ Support Vector Regressor (SVM)
# ---------------------------
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Scale features (important for SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train model
svm_model = SVR(kernel='rbf')  # you can also try 'linear' or 'poly'
svm_model.fit(X_train_scaled, y_train)

# Predict
svm_pred = svm_model.predict(X_test_scaled)

# Evaluate
svm_mae = mean_absolute_error(y_test, svm_pred)
svm_mse = mean_squared_error(y_test, svm_pred)
svm_r2 = r2_score(y_test, svm_pred)

print("\n⚙️ Support Vector Regressor (SVM) Results")
print(f"MAE: {svm_mae:.2f}")
print(f"MSE: {svm_mse:.2f}")
print(f"R²: {svm_r2:.2f}")



⚙️ Support Vector Regressor (SVM) Results
MAE: 0.06
MSE: 0.01
R²: 0.92


In [248]:
import pickle as pkl
with open('random_forest_model.pkl','wb') as file:
    pkl.dump(rf_model,file)
